### ISSUE TITLE
incorrect response

### ISSUE THREAD

**Issue by davetropeano** [eviltik/ripe-extract#1]
Returned data does not seem to always be correct:

```
$ ripe-extract --cidr "DigitalOcean"
64.119.129.228/30
89.187.117.192/27
```

The IP address `64.119.129.228` which belongs to that cidr block is part of ASN19406 which is assigned to Towerstream, not DigitalOcean. The same is true of addresses in the other cidr.

This query: `https://bgp.he.net/search?search%5Bsearch%5D=digitalocean&commit=Search` (and other ASN to cidr sites like `tcpiputils.com`) return a correct ASN and IPv4/6 list.

**Comment by eviltik** [comment]
Thank you !

2 things.

* perhaps i missed something using ripe.net API
* OR data from ripe.net does not reflect the truth (hu ??)

And

* i didn't found an API for bgp.he.net
* tcputils got an API, but it's not free

So

Perhaps you can help me to find what's wrong with ripe.net API usage, or, if you have another endpoint with a free API, then, i can change this module.

**Comment by eviltik** [comment]
Underlying API Request:

http://rest.db.ripe.net/search.json?type-filter=inetnum&flags=no-filtering&flags=resource&query-string=DigitalOcean

**Comment by davetropeano** [comment]
Thanks for the reply. I've been out of it all day (sick) and will dig deeper tomorrow.

**Comment by eviltik** [comment]
@davetropeano hi, did you take a look ?
